In [ ]:
!pip install -qU transformers optimum accelerate datasets onnx onnxruntime

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.6/11.6 MB 56.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 160.9/160.9 kB 11.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 559.1/559.1 kB 17.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.1/19.1 MB 33.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.2/19.2 MB 55.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.1/50.1 MB 11.3 MB/s eta 0:00:00

In [ ]:
import warnings
warnings.filterwarnings("ignore")
from datasets import load_dataset, Dataset
import torch
from transformers import (
    AutoTokenizer,
    AutoModelForSeq2SeqLM,
    AutoModelForCausalLM,
    DataCollatorForLanguageModeling,
    TrainingArguments,
    Trainer
)
import subprocess

print("Loading and preparing Bible chapters...")
dataset = load_dataset("SzuTao/KingJamesVersionBible", split="train")
df = dataset.to_pandas()
df = df.sort_values(by=['Book ID', 'Chapter Number', 'Verse Number'])

chapters = df.groupby(['Book', 'Chapter Number'], sort=False)['Text'].apply(' '.join).reset_index()
train_df = chapters.head(100).copy()

print("Generating synthetic target summaries...")
device = "cuda" if torch.cuda.is_available() else "cpu"

teacher_id = "facebook/bart-large-cnn"
teacher_tokenizer = AutoTokenizer.from_pretrained(teacher_id)
teacher_model = AutoModelForSeq2SeqLM.from_pretrained(teacher_id).to(device)

synthetic_summaries = []
for text in train_df['Text']:
    inputs = teacher_tokenizer(text[:3000], return_tensors="pt", max_length=1024, truncation=True).to(device)
    with torch.no_grad():
        outputs = teacher_model.generate(**inputs, max_length=60, min_length=20, do_sample=False)
    synthetic_summaries.append(teacher_tokenizer.decode(outputs[0], skip_special_tokens=True))

train_df['summary'] = synthetic_summaries
dataset_split = Dataset.from_pandas(train_df).train_test_split(test_size=0.1)

print("Preparing Student Model...")
MODEL_ID = "distilgpt2"
tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)
tokenizer.pad_token = tokenizer.eos_token

def preprocess_function(examples):
    formatted_texts = [
        f"Summarize this text:\n{doc[:2000]}\n\nSummary: {summ}{tokenizer.eos_token}"
        for doc, summ in zip(examples["Text"], examples["summary"])
    ]
    return tokenizer(formatted_texts, max_length=512, truncation=True)

tokenized_datasets = dataset_split.map(preprocess_function, batched=True)

model = AutoModelForCausalLM.from_pretrained(MODEL_ID)
data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

training_args = TrainingArguments(
    output_dir="./gpt2_bible_model",
    eval_strategy="epoch",
    learning_rate=5e-4,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    num_train_epochs=3,
    fp16=True,
    report_to="none"
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets["test"],
    data_collator=data_collator,
)

print("Starting Fine-Tuning...")
trainer.train()

trainer.save_model("./gpt2_bible_model")
tokenizer.save_pretrained("./gpt2_bible_model")

print("Exporting model to ONNX format...")
export_cmd = "optimum-cli export onnx --model ./gpt2_bible_model --task text-generation-with-past ./onnx_bible_model"
subprocess.run(export_cmd, shell=True, check=True)

tokenizer.save_pretrained("./onnx_bible_model")
print("\nPipeline Complete!")

Loading and preparing Bible chapters...

README.md:   0%|          | 0.00/58.0 [00:00<?, ?B/s]

KJV.csv:   0%|          | 0.00/4.98M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/31102 [00:00<?, ? examples/s]

Generating synthetic target summaries...

config.json:   0%|          | 0.00/1.58k [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

model.safetensors: reconstructing file:   0%|          |  0.00B / 1.63GB

model.safetensors: downloading bytes:           |  0.00B

[transformers] Please make sure the generation config includes `forced_bos_token_id=0`.

Loading weights:   0%|          | 0/511 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

Preparing Student Model...

config.json:   0%|          | 0.00/762 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

Map:   0%|          | 0/90 [00:00<?, ? examples/s]

Map:   0%|          | 0/10 [00:00<?, ? examples/s]

model.safetensors: reconstructing file:   0%|          |  0.00B /  353MB

model.safetensors: downloading bytes:           |  0.00B

Loading weights:   0%|          | 0/76 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

Starting Fine-Tuning...

[transformers] `loss_type=None` was set in the config but it is unrecognized. Using the default loss: `ForCausalLMLoss`.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Exporting model to ONNX format...

CalledProcessError: Command 'optimum-cli export onnx --model ./gpt2_bible_model --task text-generation-with-past ./onnx_bible_model' returned non-zero exit status 2.

Above is other model and single cell test script////////////////////////////////////////

In [ ]:
!pip install -q -U "optimum[exporters,onnxruntime]" transformers datasets accelerate onnx onnxruntime

WARNING: optimum 2.3.0 does not provide the extra 'exporters'
WARNING: optimum 2.3.0 does not provide the extra 'exporters'
WARNING: optimum 2.2.0 does not provide the extra 'exporters'
WARNING: optimum 2.2.0 does not provide the extra 'exporters'
WARNING: optimum 2.1.0 does not provide the extra 'exporters'
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.0/44.0 kB 3.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 161.2/161.2 kB 10.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.0/12.0 MB 113.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 559.1/559.1 kB 46.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.1/19.1 MB 102.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.2/19.2 MB 104.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.4/566.4 kB 45.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.1/50.1 MB 12.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.2/194.2 kB 19.6 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gradio 6.20.0 requires huggingface-hub<2.0,>=1.2.0, but you have huggingface-hub 0.36.2 which is incompatible.

In [ ]:
from datasets import load_dataset, Dataset
import pandas as pd
import torch
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    pipeline,
    DataCollatorForLanguageModeling,
    TrainingArguments,
    Trainer
)
import subprocess

# 2. Load and Prepare Bible Dataset
print("Loading and preparing Bible chapters...")
dataset = load_dataset("SzuTao/KingJamesVersionBible", split="train")
df = dataset.to_pandas()
df = df.sort_values(by=['Book ID', 'Chapter Number', 'Verse Number'])

# Group verses into full chapters
chapters = df.groupby(['Book', 'Chapter Number'], sort=False)['Text'].apply(' '.join).reset_index()
train_df = chapters.head(100).copy()

# 3. Generate Target Summaries using teacher model
print("Generating synthetic target summaries...")
teacher_pipe = pipeline(
    "text-generation",
    model="HuggingFaceTB/SmolLM2-1.7B-Instruct",
    device=0 if torch.cuda.is_available() else -1,
    torch_dtype=torch.float16  # float16 is fine here because this model is only used for inference
)

synthetic_summaries = []
for text in train_df['Text']:
    prompt = f"Summarize this Bible chapter concisely in 2 sentences:\n{text[:2000]}\n\nSummary:"
    res = teacher_pipe(prompt, max_new_tokens=60, return_full_text=False, do_sample=False)
    synthetic_summaries.append(res[0]['generated_text'].strip())

train_df['summary'] = synthetic_summaries

# Convert to HF Dataset format
hf_dataset = Dataset.from_pandas(train_df)
dataset_split = hf_dataset.train_test_split(test_size=0.1)

# 4. Tokenize Dataset for the Student Model
MODEL_ID = "HuggingFaceTB/SmolLM2-135M"
tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)
tokenizer.pad_token = tokenizer.eos_token

def preprocess_function(examples):
    formatted_texts = [
        f"Summarize this text:\n{doc[:2000]}\n\nSummary: {summ}{tokenizer.eos_token}"
        for doc, summ in zip(examples["Text"], examples["summary"])
    ]
    return tokenizer(formatted_texts, max_length=512, truncation=True)

tokenized_datasets = dataset_split.map(preprocess_function, batched=True)

# 5. Fine-Tune Model
# FIX: Load student model in FP32 so Trainer's fp16=True can maintain FP32 master weights
model = AutoModelForCausalLM.from_pretrained(MODEL_ID, torch_dtype=torch.float32)
data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

training_args = TrainingArguments(
    output_dir="./causal_bible_model",
    eval_strategy="epoch",
    learning_rate=5e-4,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    num_train_epochs=3,
    fp16=True,  # Enables mixed precision with proper FP32 master weights
    report_to="none"
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets["test"],
    data_collator=data_collator,
)

print("Starting Fine-Tuning...")
trainer.train()

# Save native PyTorch checkpoint
trainer.save_model("./causal_bible_model")
tokenizer.save_pretrained("./causal_bible_model")

Loading and preparing Bible chapters...

README.md:   0%|          | 0.00/58.0 [00:00<?, ?B/s]

KJV.csv: 0.00B [00:00, ?B/s]

Generating train split:   0%|          | 0/31102 [00:00<?, ? examples/s]

Generating synthetic target summaries...

config.json:   0%|          | 0.00/908 [00:00<?, ?B/s]

`torch_dtype` is deprecated! Use `dtype` instead!

model.safetensors:   0%|          | 0.00/3.42G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/132 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/655 [00:00<?, ?B/s]

Device set to use cuda:0
The following generation flags are not valid and may be ignored: ['temperature']. Set `TRANSFORMERS_VERBOSITY=info` for more details.
You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/831 [00:00<?, ?B/s]

Map:   0%|          | 0/90 [00:00<?, ? examples/s]

Map:   0%|          | 0/10 [00:00<?, ? examples/s]

config.json:   0%|          | 0.00/704 [00:00<?, ?B/s]

`torch_dtype` is deprecated! Use `dtype` instead!

model.safetensors:   0%|          | 0.00/269M [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/111 [00:00<?, ?B/s]

Starting Fine-Tuning...

('./causal_bible_model/tokenizer_config.json',
 './causal_bible_model/special_tokens_map.json',
 './causal_bible_model/vocab.json',
 './causal_bible_model/merges.txt',
 './causal_bible_model/added_tokens.json',
 './causal_bible_model/tokenizer.json')

In [ ]:
from transformers import AutoConfig, AutoTokenizer
from optimum.exporters.onnx import main_export
import subprocess

model_dir = "./causal_bible_model"
onnx_dir = "./onnx_bible_model"

# 1. Hard-patch the config to force standard PyTorch math (Eager Attention).
# This permanently bypasses the SDPA tracing bug that causes the TorchExportError.
print("Patching configuration to disable SDPA...")
config = AutoConfig.from_pretrained(model_dir)
config._attn_implementation = "eager"
config.save_pretrained(model_dir)

# 2. Export to ONNX using the Python API to avoid optimum-cli crash bugs
print("Exporting PyTorch model to ONNX format (this may take a minute)...")
main_export(
    model_name_or_path=model_dir,
    output=onnx_dir,
    task="text-generation-with-past"
)

# 3. Ensure the tokenizer is bundled with the ONNX files
print("Saving tokenizer...")
tokenizer = AutoTokenizer.from_pretrained(model_dir)
tokenizer.save_pretrained(onnx_dir)

# 4. Zip the output
print("Zipping the ONNX model for download...")
subprocess.run(f"zip -r {onnx_dir}.zip {onnx_dir}", shell=True, check=True)

print(f"\nSuccess! You can now download {onnx_dir}.zip from the files tab.")

Multiple distributions found for package optimum. Picked distribution: optimum-onnx
Flax classes are deprecated and will be removed in Diffusers v0.40.0. We recommend migrating to PyTorch classes or pinning your version of Diffusers.
Flax classes are deprecated and will be removed in Diffusers v0.40.0. We recommend migrating to PyTorch classes or pinning your version of Diffusers.

Patching configuration to disable SDPA...
Exporting PyTorch model to ONNX format (this may take a minute)...

/usr/local/lib/python3.12/dist-packages/transformers/cache_utils.py:132: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if not self.is_initialized or self.keys.numel() == 0:
/usr/local/lib/python3.12/dist-packages/transformers/masking_utils.py:207: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if (padding_length := kv_length + kv_offset - attention_mask.shape[-1]) > 0:
/usr/local/lib/python3.12/dist-packages/transformers/masking_utils.py:235: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if padding_mask is not None and padding_mask.shape[-1] > kv_length:
/usr/local/lib/python3.12/dist-packages/transformers/integrations/sdpa_attention.py:81: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  is_causal = query.shape[2] > 1 and attention_mask is None and getattr(module, "is_causal", True)
/usr/local/lib/python3.12/dist-packages/torch/onnx/_internal/torchscript_exporter/symbolic_opset11.py:954: UserWarning: Exporting aten::index operator of advanced indexing in opset 18 is achieved by combination of multiple ONNX operators, including Reshape, Transpose, Concat, and Gather. If indices include negative values, the exported graph will produce incorrect results.
  return opset9.index(g, self, index)
Found different candidate ONNX initializers (likely duplicate) for the tied weights:
	lm_head.weight: {'onnx::MatMul_9817'}
	model.embed_tokens.weight: {'model.embed_tokens.weight'}
		-[x] values not close enough, max diff: 0.0031604766845703125 (atol: 1e-05)
		-[x] values not close enough, max diff: 2.4378299713134766e-05 (atol: 1e-05)
		-[x] values not close enough, max diff: 2.6226043701171875e-05 (atol: 1e-05)
		-[x] values not close enough, max diff: 2.956390380859375e-05 (atol: 1e-05)
		-[x] values not close enough, max diff: 1.284480094909668e-05 (atol: 1e-05)
		-[x] values not close enough, max diff: 3.24249267578125e-05 (atol: 1e-05)
		-[x] values not close enough, max diff: 3.457069396972656e-05 (atol: 1e-05)
		-[x] values not close enough, max diff: 1.7642974853515625e-05 (atol: 1e-05)
		-[x] values not close enough, max diff: 4.1961669921875e-05 (atol: 1e-05)
		-[x] values not close enough, max diff: 1.309812068939209e-05 (atol: 1e-05)
		-[x] values not close enough, max diff: 5.626678466796875e-05 (atol: 1e-05)
		-[x] values not close enough, max diff: 1.710653305053711e-05 (atol: 1e-05)
		-[x] values not close enough, max diff: 8.726119995117188e-05 (atol: 1e-05)
		-[x] values not close enough, max diff: 2.1338462829589844e-05 (atol: 1e-05)
		-[x] values not close enough, max diff: 0.000171661376953125 (atol: 1e-05)
		-[x] values not close enough, max diff: 8.177757263183594e-05 (atol: 1e-05)
		-[x] values not close enough, max diff: 0.00020313262939453125 (atol: 1e-05)
		-[x] values not close enough, max diff: 8.797645568847656e-05 (atol: 1e-05)
		-[x] values not close enough, max diff: 0.000186920166015625 (atol: 1e-05)
		-[x] values not close enough, max diff: 8.231401443481445e-05 (atol: 1e-05)
		-[x] values not close enough, max diff: 0.00021028518676757812 (atol: 1e-05)
		-[x] values not close enough, max diff: 0.0001704096794128418 (atol: 1e-05)
		-[x] values not close enough, max diff: 0.00023746490478515625 (atol: 1e-05)
		-[x] values not close enough, max diff: 0.0002091526985168457 (atol: 1e-05)
		-[x] values not close enough, max diff: 0.0002650618553161621 (atol: 1e-05)
		-[x] values not close enough, max diff: 0.00017011165618896484 (atol: 1e-05)
		-[x] values not close enough, max diff: 0.00035685300827026367 (atol: 1e-05)
		-[x] values not close enough, max diff: 0.0002308487892150879 (atol: 1e-05)
		-[x] values not close enough, max diff: 0.00044608116149902344 (atol: 1e-05)
		-[x] values not close enough, max diff: 0.00022983551025390625 (atol: 1e-05)
		-[x] values not close enough, max diff: 0.00028514862060546875 (atol: 1e-05)
		-[x] values not close enough, max diff: 0.0002967715263366699 (atol: 1e-05)
		-[x] values not close enough, max diff: 0.00018453598022460938 (atol: 1e-05)
		-[x] values not close enough, max diff: 0.0002568364143371582 (atol: 1e-05)
		-[x] values not close enough, max diff: 0.0002576112747192383 (atol: 1e-05)
		-[x] values not close enough, max diff: 0.00020682811737060547 (atol: 1e-05)
		-[x] values not close enough, max diff: 0.0002675056457519531 (atol: 1e-05)
		-[x] values not close enough, max diff: 0.0003535747528076172 (atol: 1e-05)
		-[x] values not close enough, max diff: 0.00039845705032348633 (atol: 1e-05)
		-[x] values not close enough, max diff: 0.0005393028259277344 (atol: 1e-05)
		-[x] values not close enough, max diff: 0.0002903938293457031 (atol: 1e-05)
		-[x] values not close enough, max diff: 0.0005267560482025146 (atol: 1e-05)
		-[x] values not close enough, max diff: 0.00045490264892578125 (atol: 1e-05)
		-[x] values not close enough, max diff: 0.0005303621292114258 (atol: 1e-05)
		-[x] values not close enough, max diff: 0.0003373771905899048 (atol: 1e-05)
		-[x] values not close enough, max diff: 0.0007329955697059631 (atol: 1e-05)
		-[x] values not close enough, max diff: 0.0006518363952636719 (atol: 1e-05)
		-[x] values not close enough, max diff: 0.0006275177001953125 (atol: 1e-05)
		-[x] values not close enough, max diff: 0.000530242919921875 (atol: 1e-05)
		-[x] values not close enough, max diff: 0.0009419918060302734 (atol: 1e-05)
		-[x] values not close enough, max diff: 0.0005104541778564453 (atol: 1e-05)
		-[x] values not close enough, max diff: 0.0012860298156738281 (atol: 1e-05)
The ONNX export succeeded with the warning: The maximum absolute difference between the output of the reference model and the ONNX exported model is not within the set tolerance 1e-05:
- logits: max diff = 0.0031604766845703125
- present.3.key: max diff = 2.4378299713134766e-05
- present.4.key: max diff = 2.6226043701171875e-05
- present.5.key: max diff = 2.956390380859375e-05
- present.5.value: max diff = 1.284480094909668e-05
- present.6.key: max diff = 3.24249267578125e-05
- present.7.key: max diff = 3.457069396972656e-05
- present.7.value: max diff = 1.7642974853515625e-05
- present.8.key: max diff = 4.1961669921875e-05
- present.8.value: max diff = 1.309812068939209e-05
- present.9.key: max diff = 5.626678466796875e-05
- present.9.value: max diff = 1.710653305053711e-05
- present.10.key: max diff = 8.726119995117188e-05
- present.10.value: max diff = 2.1338462829589844e-05
- present.11.key: max diff = 0.000171661376953125
- present.11.value: max diff = 8.177757263183594e-05
- present.12.key: max diff = 0.00020313262939453125
- present.12.value: max diff = 8.797645568847656e-05
- present.13.key: max diff = 0.000186920166015625
- present.13.value: max diff = 8.231401443481445e-05
- present.14.key: max diff = 0.00021028518676757812
- present.14.value: max diff = 0.0001704096794128418
- present.15.key: max diff = 0.00023746490478515625
- present.15.value: max diff = 0.0002091526985168457
- present.16.key: max diff = 0.0002650618553161621
- present.16.value: max diff = 0.00017011165618896484
- present.17.key: max diff = 0.00035685300827026367
- present.17.value: max diff = 0.0002308487892150879
- present.18.key: max diff = 0.00044608116149902344
- present.18.value: max diff = 0.00022983551025390625
- present.19.key: max diff = 0.00028514862060546875
- present.19.value: max diff = 0.0002967715263366699
- present.20.key: max diff = 0.00018453598022460938
- present.20.value: max diff = 0.0002568364143371582
- present.21.key: max diff = 0.0002576112747192383
- present.21.value: max diff = 0.00020682811737060547
- present.22.key: max diff = 0.0002675056457519531
- present.22.value: max diff = 0.0003535747528076172
- present.23.key: max diff = 0.00039845705032348633
- present.23.value: max diff = 0.0005393028259277344
- present.24.key: max diff = 0.0002903938293457031
- present.24.value: max diff = 0.0005267560482025146
- present.25.key: max diff = 0.00045490264892578125
- present.25.value: max diff = 0.0005303621292114258
- present.26.key: max diff = 0.0003373771905899048
- present.26.value: max diff = 0.0007329955697059631
- present.27.key: max diff = 0.0006518363952636719
- present.27.value: max diff = 0.0006275177001953125
- present.28.key: max diff = 0.000530242919921875
- present.28.value: max diff = 0.0009419918060302734
- present.29.key: max diff = 0.0005104541778564453
- present.29.value: max diff = 0.0012860298156738281.
 The exported model was saved at: onnx_bible_model

Saving tokenizer...
Zipping the ONNX model for download...

Success! You can now download ./onnx_bible_model.zip from the files tab.